format_version: 10
pipelines:
  test-from-scm:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-200dd6f:
        git: https://github.com/prima101112/gilak
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - running build
                command: echo
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-deplloy-to-deployments:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - this is running deployments
                command: echo
                run_if: passed
    - run-kubectl-from-agent:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-deplloy-to-deployments:
            timeout: 0
            tasks:
            - exec:
                command: kubectl
                run_if: passed
